# Generated by Django 3.0.4 on 2020-04-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=40)),
                ('f_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'entrenador',
                'verbose_name_plural': 'entrenadores',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('presupuesto', models.IntegerField()),
                ('presidente', models.CharField(max_length=40)),
                ('estadio', models.CharField(max_length=40)),
                ('titulos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('f_creacion', models.DateField()),
                ('presidente', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'liga',
                'verbose_name_plural': 'ligas',
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('equipo_local', models.CharField(max_length=40)),
                ('equipo_visitante', models.CharField(max_length=40)),
                ('goles', models.IntegerField()),
                ('id_liga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campeonato.Liga')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=40)),
                ('f_nacimiento', models.DateField()),
                ('posicion', models.CharField(max_length=40)),
                ('id_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campeonato.Entrenador')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campeonato.Equipo')),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
            },
        ),
        migrations.CreateModel(
            name='Juega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=40)),
                ('id_equipo', models.ManyToManyField(to='campeonato.Equipo')),
                ('id_partido', models.ManyToManyField(to='campeonato.Partidos')),
            ],
            options={
                'verbose_name': 'juega',
                'verbose_name_plural': 'juegas',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campeonato.Liga'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='id_equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='campeonato.Equipo'),
        ),
    ]
