# Generated by Django 3.0.4 on 2020-04-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='equipo_local',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_local', to='campeonato.Equipo'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='equipo_visitante',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_visitante', to='campeonato.Equipo'),
        ),
    ]
