# Generated by Django 3.0.4 on 2020-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_auto_20200428_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
