# Generated by Django 3.0.4 on 2020-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_imagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'jugador', 'verbose_name_plural': 'jugadores'},
        ),
    ]
