# Generated by Django 3.0.4 on 2020-05-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0005_auto_20200522_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
