# Generated by Django 3.0.4 on 2020-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0006_auto_20200522_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(null=True),
        ),
    ]
