# Generated by Django 3.0.4 on 2020-06-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0009_auto_20200608_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='id_entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.Entrenador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.Equipo'),
        ),
    ]
