# Generated by Django 3.0.4 on 2020-06-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0010_auto_20200610_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
