# Generated by Django 3.0.4 on 2020-06-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0011_delete_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='id_entrenador',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='id_equipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campeonato.Equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campeonato.Liga'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campeonato.Equipo'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='equipo_local',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_local', to='campeonato.Equipo'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_visitante', to='campeonato.Equipo'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='id_liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campeonato.Liga'),
        ),
    ]
