# Generated by Django 3.0.4 on 2020-06-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0014_auto_20200617_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-puntos'], 'verbose_name': 'equipo', 'verbose_name_plural': 'equipos'},
        ),
    ]
