# Generated by Django 3.0.4 on 2020-06-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0016_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
